#!/bin/bash

echo ""
echo "This script copies a udev rule to /etc to facilitate bringing"
echo "up the roch usb connection as /dev/roch."
echo ""

sudo cp `rospack find roch_ftdi`/57-roch-laptop.rules /etc/udev/rules.d


echo ""
echo "Restarting udev"
echo ""
sudo service udev reload
sudo service udev restart

